name: remimder_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  intl: ^0.18.0

flutter:
  uses-material-design: true

  
